# Molly Ryan
# 11 August 2023
# Marker Class

import mysql.connector

class Marker:
    """ Class that compares the equivalence of MySQL queries."""
    
    def __init__(self,db):
        self.database = db
    
    def markQuery(self, studentQuery, modalQuery):
        """
        Checks if the studentQuery returns the same output as the modalQuery. Returns an array,
        wherein the first item is a Boolean indicating True if the outputs are identical. If False,
        a second item in the array is a string communicating if the studentQuery is valid and produced
        an incorrect output, or if it is invalid and the server threw an error.
        """
        database = mysql.connector.connect(
            host=self.database.host,
            user=self.database.user,
            password=self.database.pword,
            database=self.database.db_name
        )
        
        cursor = database.cursor()  # Create a cursor to interact with the database
        
        try: 
            cursor.execute(studentQuery)
            studentAnswer = cursor.fetchall()
            # Feedback to let the user know the query they entered did run. Displayed if 
            # answers do not match.
            validity = "The output generated by your query does not match the expected output."
        except: # if the studentAnswer causes the server to throw an error
            studentAnswer = ""
            # Feedback to let the user know the query they entered is not valid. Displayed if 
            # answers do not match.
            validity="The entered query is invalid. Look carefully at your syntax, and ensure names are spelt correctly and exist in the database."
        
        cursor.execute(modalQuery)
        modalAnswer = cursor.fetchall()
        headers = [tuple(i[0] for i in cursor.description)]
        
        if (studentAnswer==modalAnswer): # correct! Identical output
            return [True, "Your query produced the correct output.", headers + modalAnswer]
        
        return [False, validity, headers + modalAnswer] # output not the same 
